2023-12-16 22:58:16,402 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-12-16 22:58:16,402 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-12-16 22:58:16,403 INFO werkzeug MainThread :  * Restarting with stat
2023-12-16 22:58:26,490 WARNING werkzeug MainThread :  * Debugger is active!
2023-12-16 22:58:26,496 INFO werkzeug MainThread :  * Debugger PIN: 104-668-716
2023-12-16 22:58:51,847 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:51] "GET /login HTTP/1.1" 200 -
2023-12-16 22:58:56,869 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:56] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
2023-12-16 22:58:57,011 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:57] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2023-12-16 22:58:57,022 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:57] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2023-12-16 22:58:57,065 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:57] "[36mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-12-16 22:58:57,085 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 22:58:57] "[36mGET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-12-16 23:00:49,583 INFO werkzeug MainThread :  * Detected change in 'c:\\python project\\app.py', reloading
2023-12-16 23:00:49,991 INFO werkzeug MainThread :  * Restarting with stat
2023-12-16 23:01:00,193 WARNING werkzeug MainThread :  * Debugger is active!
2023-12-16 23:01:00,198 INFO werkzeug MainThread :  * Debugger PIN: 104-668-716
2023-12-16 23:01:16,086 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:16] "[32mPOST /login HTTP/1.1[0m" 302 -
2023-12-16 23:01:18,941 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:18] "GET / HTTP/1.1" 200 -
2023-12-16 23:01:43,369 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:43] "GET /search HTTP/1.1" 200 -
2023-12-16 23:01:43,469 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:43] "[36mGET /static/css/search.css HTTP/1.1[0m" 304 -
2023-12-16 23:01:44,605 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:44] "GET /chat HTTP/1.1" 200 -
2023-12-16 23:01:44,615 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:44] "[36mGET /static/css/chat.css HTTP/1.1[0m" 304 -
2023-12-16 23:01:44,635 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:44] "GET /search HTTP/1.1" 200 -
2023-12-16 23:01:44,659 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [16/Dec/2023 23:01:44] "[36mGET /static/css/search.css HTTP/1.1[0m" 304 -
2023-12-16 23:05:20,437 ERROR sqlalchemy.pool.impl.QueuePool MainThread : Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\pool\base.py", line 988, in _finalize_fairy
    fairy._reset(
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\pool\base.py", line 1438, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\default.py", line 692, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2023-12-16 23:05:20,440 ERROR sqlalchemy.pool.impl.QueuePool MainThread : Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\pool\base.py", line 988, in _finalize_fairy
    fairy._reset(
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\pool\base.py", line 1438, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Dima\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\default.py", line 692, in do_rollback
    dbapi_connection.rollback()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

